export enum ErrorCode {
  // Auth
  EMAIL_TAKEN              = "EMAIL_TAKEN",
  INVALID_CREDENTIALS      = "INVALID_CREDENTIALS",
  USE_GOOGLE               = "USE_GOOGLE",
  INVALID_REFRESH_TOKEN    = "INVALID_REFRESH_TOKEN",
  INVALID_OR_EXPIRED_TOKEN = "INVALID_OR_EXPIRED_TOKEN",
  GOOGLE_TOKEN_INVALID     = "GOOGLE_TOKEN_INVALID",
  GOOGLE_AUTH_DISABLED     = "GOOGLE_AUTH_DISABLED",
  EMAIL_VERIFICATION_TOKEN_INVALID = "EMAIL_VERIFICATION_TOKEN_INVALID",
  EMAIL_VERIFICATION_TOKEN_EXPIRED = "EMAIL_VERIFICATION_TOKEN_EXPIRED",
  EMAIL_ALREADY_VERIFIED   = "EMAIL_ALREADY_VERIFIED",
  // Users
  USER_NOT_FOUND           = "USER_NOT_FOUND",
  // Workspace
  CANNOT_CHANGE_OWNER_ROLE = "CANNOT_CHANGE_OWNER_ROLE",
  CANNOT_REMOVE_OWNER      = "CANNOT_REMOVE_OWNER",
  // Domain
  NOT_FOUND                = "NOT_FOUND",
  CLIENT_NOT_FOUND         = "CLIENT_NOT_FOUND",
  PROJECT_NOT_FOUND        = "PROJECT_NOT_FOUND",
  MEETING_NOT_FOUND        = "MEETING_NOT_FOUND",
  OPPORTUNITY_NOT_FOUND    = "OPPORTUNITY_NOT_FOUND",
  BRIEFING_NOT_FOUND       = "BRIEFING_NOT_FOUND",
  FOLLOWUP_NOT_FOUND       = "FOLLOWUP_NOT_FOUND",
  VERSION_NOT_FOUND        = "VERSION_NOT_FOUND",
  STATE_NOT_FOUND          = "STATE_NOT_FOUND",
  CITY_NOT_FOUND           = "CITY_NOT_FOUND",
  MEDIA_LIMIT_REACHED      = "MEDIA_LIMIT_REACHED",
  DOCUMENT_NOT_FOUND       = "DOCUMENT_NOT_FOUND",
  DOCUMENT_FOLDER_NOT_FOUND = "DOCUMENT_FOLDER_NOT_FOUND",
  AUTOMATION_NOT_FOUND     = "AUTOMATION_NOT_FOUND",
  TASK_NOT_FOUND           = "TASK_NOT_FOUND",
  CROSS_TENANT_REFERENCE   = "CROSS_TENANT_REFERENCE",
  // Billing
  SUBSCRIPTION_NOT_FOUND   = "SUBSCRIPTION_NOT_FOUND",
  SUBSCRIPTION_ALREADY_EXISTS = "SUBSCRIPTION_ALREADY_EXISTS",
}

export class AppError extends Error {
  constructor(public readonly code: ErrorCode, message?: string) {
    super(message ?? code)
    this.name = "AppError"
  }
}
