export enum ErrorCode {
  // Auth
  EMAIL_TAKEN              = "EMAIL_TAKEN",
  INVALID_CREDENTIALS      = "INVALID_CREDENTIALS",
  USE_GOOGLE               = "USE_GOOGLE",
  INVALID_REFRESH_TOKEN    = "INVALID_REFRESH_TOKEN",
  INVALID_OR_EXPIRED_TOKEN = "INVALID_OR_EXPIRED_TOKEN",
  GOOGLE_TOKEN_INVALID     = "GOOGLE_TOKEN_INVALID",
  GOOGLE_AUTH_DISABLED     = "GOOGLE_AUTH_DISABLED",
  EMAIL_VERIFICATION_TOKEN_INVALID = "EMAIL_VERIFICATION_TOKEN_INVALID",
  EMAIL_VERIFICATION_TOKEN_EXPIRED = "EMAIL_VERIFICATION_TOKEN_EXPIRED",
  EMAIL_ALREADY_VERIFIED   = "EMAIL_ALREADY_VERIFIED",
  // Users
  USER_NOT_FOUND           = "USER_NOT_FOUND",
  // Workspace
  CANNOT_CHANGE_OWNER_ROLE = "CANNOT_CHANGE_OWNER_ROLE",
  CANNOT_REMOVE_OWNER      = "CANNOT_REMOVE_OWNER",
  INVITE_EMAIL_MISMATCH    = "INVITE_EMAIL_MISMATCH",
  ALREADY_IN_WORKSPACE     = "ALREADY_IN_WORKSPACE",
  // Domain
  NOT_FOUND                = "NOT_FOUND",
  CLIENT_NOT_FOUND         = "CLIENT_NOT_FOUND",
  PROJECT_NOT_FOUND        = "PROJECT_NOT_FOUND",
  MEETING_NOT_FOUND        = "MEETING_NOT_FOUND",
  OPPORTUNITY_NOT_FOUND    = "OPPORTUNITY_NOT_FOUND",
  BRIEFING_NOT_FOUND       = "BRIEFING_NOT_FOUND",
  FOLLOWUP_NOT_FOUND       = "FOLLOWUP_NOT_FOUND",
  VERSION_NOT_FOUND        = "VERSION_NOT_FOUND",
  STATE_NOT_FOUND          = "STATE_NOT_FOUND",
  CITY_NOT_FOUND           = "CITY_NOT_FOUND",
  MEDIA_LIMIT_REACHED      = "MEDIA_LIMIT_REACHED",
  DOCUMENT_NOT_FOUND       = "DOCUMENT_NOT_FOUND",
  DOCUMENT_FOLDER_NOT_FOUND = "DOCUMENT_FOLDER_NOT_FOUND",
  AUTOMATION_NOT_FOUND     = "AUTOMATION_NOT_FOUND",
  TASK_NOT_FOUND           = "TASK_NOT_FOUND",
  CROSS_TENANT_REFERENCE   = "CROSS_TENANT_REFERENCE",
  PROPOSAL_TEMPLATE_NOT_FOUND  = "PROPOSAL_TEMPLATE_NOT_FOUND",
  PROPOSAL_SECTION_NOT_FOUND   = "PROPOSAL_SECTION_NOT_FOUND",
  PROPOSAL_BLOCK_NOT_FOUND     = "PROPOSAL_BLOCK_NOT_FOUND",
  PROPOSAL_NARRATIVE_NOT_FOUND = "PROPOSAL_NARRATIVE_NOT_FOUND",
  SECTION_INSTANCE_NOT_FOUND   = "SECTION_INSTANCE_NOT_FOUND",
  PROPOSAL_PROJECT_NOT_LINKED  = "PROPOSAL_PROJECT_NOT_LINKED",
  INVALID_REORDER              = "INVALID_REORDER",
  // Billing
  SUBSCRIPTION_NOT_FOUND   = "SUBSCRIPTION_NOT_FOUND",
  SUBSCRIPTION_ALREADY_EXISTS = "SUBSCRIPTION_ALREADY_EXISTS",
  BILLING_NOT_CONFIGURED   = "BILLING_NOT_CONFIGURED",
  BILLING_PLAN_NOT_FOUND   = "BILLING_PLAN_NOT_FOUND",
  BILLING_PLAN_NOT_SELLABLE = "BILLING_PLAN_NOT_SELLABLE",
  BILLING_PROVIDER_ERROR   = "BILLING_PROVIDER_ERROR",
  WEBHOOK_SIGNATURE_INVALID = "WEBHOOK_SIGNATURE_INVALID",
  // Financial (office-level AP/AR — distinct from Billing/Subscription above)
  SUPPLIER_CATEGORY_NOT_FOUND = "SUPPLIER_CATEGORY_NOT_FOUND",
  SUPPLIER_CATEGORY_NAME_TAKEN = "SUPPLIER_CATEGORY_NAME_TAKEN",
  SUPPLIER_NOT_FOUND       = "SUPPLIER_NOT_FOUND",
  BANK_ACCOUNT_NOT_FOUND   = "BANK_ACCOUNT_NOT_FOUND",
  FINANCIAL_CATEGORY_NOT_FOUND = "FINANCIAL_CATEGORY_NOT_FOUND",
  FINANCIAL_CATEGORY_NAME_TAKEN = "FINANCIAL_CATEGORY_NAME_TAKEN",
  FINANCIAL_CATEGORY_DIRECTION_MISMATCH = "FINANCIAL_CATEGORY_DIRECTION_MISMATCH",
  FINANCIAL_CATEGORY_HAS_CHILDREN = "FINANCIAL_CATEGORY_HAS_CHILDREN",
  COST_CENTER_NOT_FOUND    = "COST_CENTER_NOT_FOUND",
  COST_CENTER_NAME_TAKEN   = "COST_CENTER_NAME_TAKEN",
  FINANCIAL_DOCUMENT_NOT_FOUND = "FINANCIAL_DOCUMENT_NOT_FOUND",
  FINANCIAL_DOCUMENT_CANCELLED = "FINANCIAL_DOCUMENT_CANCELLED",
  FINANCIAL_DOCUMENT_HAS_PAYMENTS = "FINANCIAL_DOCUMENT_HAS_PAYMENTS",
  FINANCIAL_DOCUMENT_DIRECTION_CONFLICT = "FINANCIAL_DOCUMENT_DIRECTION_CONFLICT",
  INSTALLMENTS_TOTAL_MISMATCH = "INSTALLMENTS_TOTAL_MISMATCH",
  INSTALLMENT_NOT_FOUND    = "INSTALLMENT_NOT_FOUND",
  INSTALLMENT_ALREADY_PAID = "INSTALLMENT_ALREADY_PAID",
  PAYMENT_EXCEEDS_REMAINING = "PAYMENT_EXCEEDS_REMAINING",
  // RC-2.3 — referential guards blocking a hard delete elsewhere in the app
  PROJECT_HAS_FINANCIAL_HISTORY = "PROJECT_HAS_FINANCIAL_HISTORY",
  CLIENT_HAS_FINANCIAL_HISTORY  = "CLIENT_HAS_FINANCIAL_HISTORY",
  // CORE-2 (Sprint 0) — same guard pattern, one hop upstream: an Opportunity/
  // Proposal that already converted to a Project can no longer be deleted
  // physically (see FINANCIAL_ARCHITECTURE_DECISIONS.md, Anexo B).
  OPPORTUNITY_HAS_PROJECT = "OPPORTUNITY_HAS_PROJECT",
  PROPOSAL_HAS_PROJECT    = "PROPOSAL_HAS_PROJECT",
  // Entity Lifecycle (ADR-020) — generic archive/restore outcomes shared by
  // every entity that delegates to entityLifecycleService.
  ENTITY_ALREADY_ARCHIVED = "ENTITY_ALREADY_ARCHIVED",
  ENTITY_NOT_ARCHIVED     = "ENTITY_NOT_ARCHIVED",
  PARENT_ARCHIVED         = "PARENT_ARCHIVED",
  // Compras (COMPRAS_ARCHITECTURE_DECISIONS.md)
  PURCHASE_ORDER_NOT_FOUND     = "PURCHASE_ORDER_NOT_FOUND",
  PURCHASE_ORDER_NOT_DRAFT     = "PURCHASE_ORDER_NOT_DRAFT",
  PURCHASE_ORDER_ALREADY_DECIDED = "PURCHASE_ORDER_ALREADY_DECIDED",
  PURCHASE_ORDER_CATEGORY_DIRECTION_MISMATCH = "PURCHASE_ORDER_CATEGORY_DIRECTION_MISMATCH",
  // Worklog (WORKLOG_ARCHITECTURE_DECISIONS.md)
  TIME_ENTRY_NOT_FOUND     = "TIME_ENTRY_NOT_FOUND",
  TIMER_ALREADY_RUNNING    = "TIMER_ALREADY_RUNNING",
  TIMER_NOT_ACTIVE         = "TIMER_NOT_ACTIVE",
  TIMER_NOT_PAUSED         = "TIMER_NOT_PAUSED",
  TIME_ENTRY_NOT_EDITABLE  = "TIME_ENTRY_NOT_EDITABLE",
  TIME_ENTRY_ACTIVE_CANNOT_ARCHIVE = "TIME_ENTRY_ACTIVE_CANNOT_ARCHIVE",
  ACTIVITY_CATEGORY_NOT_FOUND = "ACTIVITY_CATEGORY_NOT_FOUND",
  ACTIVITY_CATEGORY_NAME_TAKEN = "ACTIVITY_CATEGORY_NAME_TAKEN",
  // Kanban Sprint — Fase A (MEL-04): optimistic concurrency. Thrown when a
  // caller supplies expectedUpdatedAt and the record was modified by someone
  // else in the meantime — see opportunity.service.ts/project.service.ts.
  STALE_WRITE = "STALE_WRITE",
}

export class AppError extends Error {
  constructor(public readonly code: ErrorCode, message?: string) {
    super(message ?? code)
    this.name = "AppError"
  }
}
